import "../styles/index.css";
import type { AppProps } from "next/app";
import Layout from "../components/common/Layout";
import { wrapper } from "../store/index";
import Head from "next/head";
import { useSelector } from "react-redux";

function MyApp({ Component, pageProps }: AppProps) {
  const { title } = useSelector((state: any) => state.title);
  return (
    <>
      <Head>
        <title>{title || "kough.kr"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0,user-scalable=0"
        />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href={`https://fonts.googleapis.com/css2?family=Noto+Sans+KR&family=Permanent+Marker&display=swap`}
          rel="stylesheet"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Component {...pageProps} />
      </Layout>
    </>
  );
}

export default wrapper.withRedux(MyApp);
