import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import MainLayout from "../components/common/main/MainLayout";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>kough.kr</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0,user-scalable=0"
        />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href={`https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap`}
          rel="stylesheet"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout />
    </div>
  );
};

export default Home;
